#ifndef WMSYNC__ERRORS_H
#define WMSYNC__ERRORS_H

#define WMSYNC_MEM_ALLOC_FAILED 13134
#define WMSYNC_BUF_TOO_SMALL 12213
#define WMSYNC_URL_PARSE_ERROR 11234
#define WMSYNC_HTTP_CONNECT_ERROR 23123
#define WMSYNC_HTTP_SEND_ERROR 13132

#endif // WMSYNC_ERRORS_H